[colors.bright]
black = "#686868"
blue = "#73d0ff"
cyan = "#95e6cb"
green = "#95e6cb"
magenta = "#d4bfff"
red = "#d4bfff"
white = "#ffffff"
yellow = "#ffd580"

[colors.normal]
black = "#191e2a"
blue = "#6dcbfa"
cyan = "#90e1c6"
green = "#a6cc70"
magenta = "#cfbafa"
red = "#ed8274"
white = "#c7c7c7"
yellow = "#fad07b"

[colors.primary]
background = "#1f2430"
foreground = "#cbccc6"


# Font configuration
[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }









